### ISSUE TITLE
Extend with child theme

### ISSUE THREAD

**Issue by kekko1212** [dxw/govuk-theme#40]
Hi, I am currently trying to extend this theme with a child one, and although I am following all the requirements to create and extend a parent theme, this does not work with this theme.

My child style.css looks like:

```
/*
 * Theme Name: GovukTheme Child
 * Author: Someone
 * Version: 0.0.1
 * License: MIT
 * Template: govuk-theme-main
 * Text domain: govuk-theme-child
 */
```

This is my folder structure:

![image](https://user-images.githubusercontent.com/5764575/132693659-d44709a1-c4eb-4c4c-bedc-dbdc94cd9877.png)

and what I get in the WP dashboard (themes section) is:

![image](https://user-images.githubusercontent.com/5764575/132654237-7e8bbded-9be6-41da-be44-4ecee8bfc016.png)

I've tried extending other parent themes, and that works just fine.

I wonder if it is mainly due to the fact that this theme structure is a bit different from other WP themes, in fact, the `style.css` file in the `govuk-theme` is in the `templates` folder, not in the root.

**Comment by RobjS** [comment]
Hi, sorry it's taken us so long to get back to you on this.

You're right, this is due to the different theme structure. You should find that if you use `Template: govuk-theme/templates` in your child style.css (rather than `Template: govuk-theme`) the child/parent relation will work as expected.
